force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <label>Resume</label>
    <nameField>
        <displayFormat>res-{000000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resume</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <label>Expected Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/LinkedIn_URL__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_URL__c</fullName>
    <label>LinkedIn URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Preferred_Location__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Location__c</fullName>
    <label>Preferred Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Primary_Skills__c.field-meta.xml
<CustomField>
    <fullName>Primary_Skills__c</fullName>
    <label>Primary Skills</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Secondary_Skills__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Skills__c</fullName>
    <label>Secondary Skills</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Willing_to_Relocate__c.field-meta.xml
<CustomField>
    <fullName>Willing_to_Relocate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Willing to Relocate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Work_Experience__c.field-meta.xml
<CustomField>
    <fullName>Work_Experience__c</fullName>
    <label>Work Experience</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Resume__c/fields/Year_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Experience__c</fullName>
    <label>Year of Experience</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResumeFormController.cls
public with sharing class ResumeFormController {
   @AuraEnabled
public static Id createResumeRecord(String fullName, String email, Double phone, Integer experience,
                                   String location, String linkedin, String role, String summary,
                                   String primarySkills, String secondarySkills, Boolean willingToRelocate,
                                   Decimal expectedSalary, String education, String workExperience) {
   Resume__c resume = new Resume__c(
       Full_Name__c = fullName,
       Email__c = email,
       Phone__c = phone,
       Year_of_Experience__c = experience,
       Preferred_Location__c = location,
       LinkedIn_URL__c = linkedin,
       Job_Role__c = role,
       Summary__c = summary,
       Primary_Skills__c = primarySkills,
       Secondary_Skills__c = secondarySkills,
       Willing_to_Relocate__c = willingToRelocate,
       Expected_Salary__c = expectedSalary,
       Education__c = education,
       Work_Experience__c = workExperience
   );
   insert resume;
   return resume.Id;
}
}